// resources/js/Pages/Chirps/Create.jsx
import React, { useState } from 'react';
import { useForm } from '@inertiajs/react';

export default function CreateChirp() {
  const { data, setData, post } = useForm({
    content: '',
    file: null,
  });

  const handleFileChange = (e) => {
    setData('file', e.target.files[0]);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    post(route('chirps.store'));
  };

  return (
    <form onSubmit={handleSubmit} encType="multipart/form-data">
      <textarea
        value={data.content}
        onChange={(e) => setData('content', e.target.value)}
        placeholder="Write your chirp here"
      />
      <input type="file" onChange={handleFileChange} accept="image/*,video/*" />
      <button type="submit">Post Chirp</button>
    </form>
  );
}

// resources/js/Pages/Chirps/Create.vue
<template>
  <form @submit.prevent="submitForm" enctype="multipart/form-data">
    <textarea v-model="form.content" placeholder="Write your chirp here"></textarea>
    <input type="file" @change="handleFile" accept="image/*,video/*">
    <button type="submit">Post Chirp</button>
  </form>
</template>

<script>
import { reactive } from 'vue';
import { useForm } from '@inertiajs/inertia-vue3';

export default {
  setup() {
    const form = useForm({
      content: '',
      file: null,
    });

    const handleFile = (event) => {
      form.file = event.target.files[0];
    };

    const submitForm = () => {
      form.post(route('chirps.store'));
    };

    return { form, handleFile, submitForm };
  },
};
</script>
