// resources/js/Pages/Chirps/Show.vue
<template>
    <div>
      <p>{{ chirp.content }}</p>
      <img v-if="chirp.file_path && chirp.file_path.endsWith('.png')" :src="chirp.file_url" alt="Chirp Image" />
      <video v-if="chirp.file_path && chirp.file_path.endsWith('.mp4')" controls>
        <source :src="chirp.file_url" type="video/mp4" />
      </video>
    </div>
  </template>
  
  <script>
  export default {
    props: {
      chirp: Object,
    },
  };
  </script>

// resources/js/Pages/Chirps/Show.jsx
import React from 'react';

export default function ShowChirp({ chirp }) {
  return (
    <div>
      <p>{chirp.content}</p>
      {chirp.file_path && chirp.file_path.endsWith('.png') && (
        <img src={chirp.file_url} alt="Chirp Image" />
      )}
      {chirp.file_path && chirp.file_path.endsWith('.mp4') && (
        <video controls>
          <source src={chirp.file_url} type="video/mp4" />
        </video>
      )}
    </div>
  );
}
